import { WizardStep } from "./types";

export const TOTAL_STEPS = 6;

export const WIZARD_STEPS: WizardStep[] = [
  {
    id: 1,
    title: "Your Profile",
    description: "Tell us about yourself.",
  },
  {
    id: 2,
    title: "Location",
    description: "Choose your country and language.",
  },
  {
    id: 3,
    title: "Interests",
    description: "Select topics you enjoy.",
  },
  {
    id: 4,
    title: "Goals",
    description: "What brings you here?",
  },
  {
    id: 5,
    title: "Personality",
    description: "Help us match you better.",
  },
  {
    id: 6,
    title: "Finish",
    description: "Review and complete setup.",
  },
];

export const INTEREST_OPTIONS = [
  "Artificial Intelligence",
  "Programming",
  "Technology",
  "Cybersecurity",
  "Data Science",
  "Business",
  "Entrepreneurship",
  "Startups",
  "Finance",
  "Investing",
  "Marketing",
  "Sales",
  "Education",
  "Research",
  "Science",
  "Health & Fitness",
  "Mental Health",
  "Medicine",
  "Books",
  "Writing",
  "Movies",
  "Music",
  "Photography",
  "Art & Design",
  "Fashion",
  "Gaming",
  "Anime",
  "Sports",
  "Football",
  "Basketball",
  "Travel",
  "Food",
  "Cooking",
  "Languages",
  "Culture",
  "History",
  "Politics",
  "Environment",
  "Climate",
  "Agriculture",
  "Religion",
  "Volunteering",
];

export const GOAL_OPTIONS = [
  "Make New Friends",
  "Professional Networking",
  "Business Partnerships",
  "Find a Mentor",
  "Become a Mentor",
  "Practice Languages",
  "Learn New Skills",
  "Career Growth",
  "Job Opportunities",
  "Share Knowledge",
  "Discuss Ideas",
  "Daily Conversations",
  "Join Study Groups",
  "Travel Companions",
  "Dating",
  "Community Building",
];
export const PERSONALITY_OPTIONS = [
  {
    id: "introvert",
    title: "Introvert",
    description: "Prefer meaningful one-on-one conversations.",
  },
  {
    id: "ambivert",
    title: "Ambivert",
    description: "Comfortable in both quiet and social settings.",
  },
  {
    id: "extrovert",
    title: "Extrovert",
    description: "Love meeting people and joining lively discussions.",
  },
];
export const LANGUAGE_OPTIONS = [
  "English",
  "French",
  "Spanish",
  "Portuguese",
  "Arabic",
  "Chinese (Mandarin)",
  "Japanese",
  "Korean",
  "Russian",
  "German",
  "Italian",
  "Hindi",
  "Urdu",
  "Turkish",
  "Swahili",
  "Hausa",
  "Yoruba",
  "Igbo",
];
export const COUNTRY_OPTIONS = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "Egypt",
  "Morocco",
  "Ethiopia",
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Brazil",
  "Mexico",
  "India",
  "Pakistan",
  "Bangladesh",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Australia",
  "New Zealand",
];
export const AGE_GROUP_OPTIONS = [
  "18-24",
  "25-34",
  "35-44",
  "45-54",
  "55+",
];
export const OCCUPATION_OPTIONS = [
  "Student",
  "Software Developer",
  "Designer",
  "Entrepreneur",
  "Teacher",
  "Healthcare Professional",
  "Engineer",
  "Researcher",
  "Content Creator",
  "Marketing Professional",
  "Sales Professional",
  "Government Employee",
  "Farmer",
  "Freelancer",
  "Other",
];
export const AVAILABILITY_OPTIONS = [
  "Morning",
  "Afternoon",
  "Evening",
  "Night",
  "Weekends",
  "Flexible",
];