[build]
  publish = "public"
  functions = "netlify/functions"
  command = "mkdir -p public && cp *.html public/ && cp *.css public/ && cp *.js public/ && cp favicon.ico public/"

[functions]
  node_version = "18"
  node_bundler = "esbuild"
  included_files = ["public/data/*.json"]

# Reliable SPA Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions:
    Status = "404-410"

[[redirects]]
  from = "/liked_movies/*"
  to = "/index.html"
  status = 200

# Error Handling
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Security Headers (Optimized)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' api.themoviedb.org www.googletagmanager.com; script-src 'self' 'unsafe-inline'; style-src 'self' fonts.googleapis.com; img-src 'self' data: image.tmdb.org; font-src 'self' fonts.gstatic.com"
    Permissions-Policy = "geolocation=(), microphone=()"

# Cache Headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"